export class GeminiService {
  private hasApiKey: boolean;

  constructor() {
    this.hasApiKey = !!process.env.GEMINI_API_KEY;
  }

  async enrich(content: string): Promise<{ summary?: string; doc_type?: string; tags?: string[] }> {
    if (!this.hasApiKey) {
      throw new Error("GEMINI_API_KEY is not set.");
    }

    // Mock implementation for the test, normally this would call the Gemini API
    if (content.includes("error")) {
      throw new Error("Simulated API error");
    }

    return {
      summary: "This is a summary generated by Gemini.",
      doc_type: "article",
      tags: ["ai", "gemini"]
    };
  }
}
