import pytest
from context_refinery.services import GeminiService

class MockGeminiService(GeminiService):
    def enrich(self, content):
        if not self.has_api_key:
            raise Exception("GEMINI_API_KEY is not set.")
        if "error" in content.lower():
            raise Exception("Simulated API error")
        return {
            "summary": "This is a summary generated by Gemini.",
            "doc_type": "article",
            "tags": ["ai", "gemini"]
        }

@pytest.fixture(autouse=True)
def mock_gemini_service_patch(monkeypatch):
    monkeypatch.setattr("context_refinery.enrichment.GeminiService", MockGeminiService)
