import pytest
from fastapi.testclient import TestClient
from api.main import app

client = TestClient(app)

def test_enrich_success(mocker):
    mocker.patch(
        "context_refinery.services.GeminiService.enrich",
        return_value={"summary": "test", "doc_type": "note", "tags": ["a"]}
    )
    response = client.post("/enrich", json={"content": "hello"})
    assert response.status_code == 200
    data = response.json()
    assert data["summary"] == "test"
    assert data["doc_type"] == "note"
    assert data["tags"] == ["a"]

def test_enrich_empty_content(mocker):
    mocker.patch(
        "context_refinery.services.GeminiService.enrich",
        return_value={"summary": "empty", "doc_type": "other", "tags": []}
    )
    response = client.post("/enrich", json={"content": ""})
    assert response.status_code == 200
    data = response.json()
    assert data["summary"] == "empty"
    assert data["doc_type"] == "other"
    assert data["tags"] == []

def test_enrich_missing_body():
    response = client.post("/enrich", json={})
    assert response.status_code == 422

def test_enrich_no_api_key(mocker):
    mocker.patch(
        "context_refinery.services.GeminiService.enrich",
        side_effect=Exception("GEMINI_API_KEY is not set...")
    )
    response = client.post("/enrich", json={"content": "hello"})
    assert response.status_code == 503
    assert "GEMINI_API_KEY not configured" in response.json()["detail"]

def mock_enrich_side_effect(content):
    if "error" in content.lower():
        raise Exception("Simulated API error")
    return {
        "summary": "This is a summary generated by Gemini.",
        "doc_type": "article",
        "tags": ["ai", "gemini"]
    }

def test_batch_enrich_success(mocker):
    mocker.patch("context_refinery.services.GeminiService.enrich", side_effect=mock_enrich_side_effect)
    response = client.post("/enrich/batch", json={
        "documents": [
            {"content": "First doc"},
            {"content": "Second doc"},
            {"content": "Third doc"}
        ]
    })
    assert response.status_code == 200
    data = response.json()
    assert data["total"] == 3
    assert data["succeeded"] == 3
    assert data["failed"] == 0
    assert len(data["results"]) == 3
    assert data["results"][0]["status"] == "success"
    assert data["results"][0]["data"]["summary"] == "This is a summary generated by Gemini."

def test_batch_enrich_partial_failure(mocker):
    mocker.patch("context_refinery.services.GeminiService.enrich", side_effect=mock_enrich_side_effect)
    response = client.post("/enrich/batch", json={
        "documents": [
            {"content": "First doc"},
            {"content": "Simulated error here"},
            {"content": "Third doc"}
        ]
    })
    assert response.status_code == 200
    data = response.json()
    assert data["total"] == 3
    assert data["succeeded"] == 2
    assert data["failed"] == 1
    assert data["results"][1]["status"] == "error"
    assert "Simulated API error" in data["results"][1]["error"]


def test_batch_enrich_empty_list():
    response = client.post("/enrich/batch", json={"documents": []})
    assert response.status_code == 422

def test_batch_enrich_over_limit():
    docs = [{"content": f"Doc {i}"} for i in range(51)]
    response = client.post("/enrich/batch", json={"documents": docs})
    assert response.status_code == 422

def test_batch_enrich_no_api_key(mocker):
    mocker.patch(
        "context_refinery.services.GeminiService.enrich",
        side_effect=Exception("GEMINI_API_KEY is not set...")
    )
    response = client.post("/enrich/batch", json={
        "documents": [{"content": "hello"}]
    })
    assert response.status_code == 503
    assert "GEMINI_API_KEY not configured" in response.json()["detail"]
