import os
import pytest
from context_refinery.enrichment import EnrichmentService, EnrichmentOptions
from context_refinery.services import GeminiService
from context_refinery.models import CanonicalDoc

@pytest.fixture
def mock_env():
    old_env = dict(os.environ)
    yield
    os.environ.clear()
    os.environ.update(old_env)

def test_enrich_document_when_key_present(mock_env):
    os.environ['GEMINI_API_KEY'] = 'test-key'
    service = EnrichmentService()
    doc = CanonicalDoc(id='1', content='Test content')

    result = service.enrich_document(doc)

    assert result.summary == 'This is a summary generated by Gemini.'
    assert result.doc_type == 'article'
    assert result.tags == ['ai', 'gemini']

def test_graceful_fallback_when_key_absent(mock_env):
    if 'GEMINI_API_KEY' in os.environ:
        del os.environ['GEMINI_API_KEY']
    service = EnrichmentService()
    doc = CanonicalDoc(id='1', content='Test content', title='Original')

    result = service.enrich_document(doc)

    assert result.summary is None
    # default doc_type is "document", not undefined, so check it stayed default
    assert result.doc_type == 'document'
    # tags default to []
    assert result.tags == []
    assert result.title == 'Original'

def test_graceful_fallback_when_api_throws_error(mock_env):
    os.environ['GEMINI_API_KEY'] = 'test-key'
    service = EnrichmentService()
    doc = CanonicalDoc(id='1', content='This content has an error')

    result = service.enrich_document(doc)

    assert result.summary is None

def test_respect_enrichment_options(mock_env):
    os.environ['GEMINI_API_KEY'] = 'test-key'
    service = EnrichmentService()
    doc = CanonicalDoc(id='1', content='Test content')

    options = EnrichmentOptions(enable_summary=False, enable_doc_type=True, enable_tags=False)
    result = service.enrich_document(doc, options=options)

    assert result.summary is None
    assert result.doc_type == 'article'
    assert result.tags == []

def test_merge_tags_properly(mock_env):
    os.environ['GEMINI_API_KEY'] = 'test-key'
    service = EnrichmentService()
    doc = CanonicalDoc(id='1', content='Test content', tags=['existing', 'ai'])

    result = service.enrich_document(doc)

    assert result.tags == ['existing', 'ai', 'gemini']
