import { EnrichmentService } from './enrichmentService';
import { GeminiService } from '../services/geminiService';
import { CanonicalDocument } from '../types';

describe('EnrichmentService', () => {
  let originalEnv: NodeJS.ProcessEnv;

  beforeEach(() => {
    originalEnv = process.env;
    process.env = { ...originalEnv };
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it('should enrich document when GEMINI_API_KEY is present', async () => {
    process.env.GEMINI_API_KEY = 'test-key';
    const service = new EnrichmentService();
    const doc: CanonicalDocument = { id: '1', content: 'Test content' };

    const result = await service.enrichDocument(doc);

    expect(result.summary).toBe('This is a summary generated by Gemini.');
    expect(result.doc_type).toBe('article');
    expect(result.tags).toEqual(['ai', 'gemini']);
  });

  it('should gracefully fallback when GEMINI_API_KEY is absent', async () => {
    delete process.env.GEMINI_API_KEY;
    const service = new EnrichmentService();
    const doc: CanonicalDocument = { id: '1', content: 'Test content', title: 'Original' };

    const result = await service.enrichDocument(doc);

    expect(result.summary).toBeUndefined();
    expect(result.doc_type).toBeUndefined();
    expect(result.tags).toBeUndefined();
    expect(result.title).toBe('Original');
  });

  it('should gracefully fallback when Gemini API throws an error', async () => {
    process.env.GEMINI_API_KEY = 'test-key';
    const service = new EnrichmentService();
    const doc: CanonicalDocument = { id: '1', content: 'This content has an error' };

    const result = await service.enrichDocument(doc);

    expect(result.summary).toBeUndefined();
  });

  it('should respect enrichment options', async () => {
    process.env.GEMINI_API_KEY = 'test-key';
    const service = new EnrichmentService();
    const doc: CanonicalDocument = { id: '1', content: 'Test content' };

    const result = await service.enrichDocument(doc, { enableSummary: false, enableDocType: true, enableTags: false });

    expect(result.summary).toBeUndefined();
    expect(result.doc_type).toBe('article');
    expect(result.tags).toBeUndefined();
  });

  it('should merge tags properly', async () => {
    process.env.GEMINI_API_KEY = 'test-key';
    const service = new EnrichmentService();
    const doc: CanonicalDocument = { id: '1', content: 'Test content', tags: ['existing', 'ai'] };

    const result = await service.enrichDocument(doc);

    expect(result.tags).toEqual(['existing', 'ai', 'gemini']);
  });
});
